// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions{
  static FirebaseOptions get currentPlatform{
    return const FirebaseOptions(
      apiKey: 'AIzaSyDwI2Mmlw20vsnH0VBItsyemMkYX7p9pkk',
      appId: '1:954274316099:android:05b79245aac9273aa379f6',
      messagingSenderId: '954274316099',
      projectId: 'sport-ease-be646',
      storageBucket: 'sport-ease-be646.firebasestorage.app',);
}
}
    
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA7rTDeHUAyoYimP-Bjv8qFiVEcszlowB0',
//     appId: '1:954274316099:web:e53517b0c65c8606a379f6',
//     messagingSenderId: '954274316099',
//     projectId: 'sport-ease-be646',
//     authDomain: 'sport-ease-be646.firebaseapp.com',
//     storageBucket: 'sport-ease-be646.firebasestorage.app',
//     measurementId: 'G-M26352QM1F',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDwI2Mmlw20vsnH0VBItsyemMkYX7p9pkk',
//     appId: '1:954274316099:android:05b79245aac9273aa379f6',
//     messagingSenderId: '954274316099',
//     projectId: 'sport-ease-be646',
//     storageBucket: 'sport-ease-be646.firebasestorage.app',
//   );
// }
